### PR TITLE
Update tbdb.csv

### PR DESCRIPTION
**Pull request by pmenzel**
Add pncA Thr142Arg

We saw this mutation reported by TB-Profiler in a pyrazinamide-resistant isolate.

I didn't find a paper mentioning this mutation, but it is mentioned in this phd thesis: https://hal.inria.fr/tel-01560449/

### CODE REVIEW

**Comment by jodyphelan** [comment]
Hi @pmenzel 

Thanks for reporting the mutation I've had a look and here are my thoughts.



# Mutation confidence results
### Mutations added
| Drug | Gene | Mutation | Literature | # Isolates | Lineage | OR | OR-pval | LR | LR-pval | confidence |
|-|-|-|-|-|-|-|-|-|-|-|
|pyrazinamide|pncA|p.Thr142Arg|https://hal.inria.fr/tel-01560449/|1|lineage4.6.1.2:1|NA|NA|NA|NA|indeterminate|

### Literature evidence
Mutation seen in https://hal.inria.fr/tel-01560449/ in an isolate from Vietnam belonging to the Beijing family with drug resistance pattern MDR+Str+Emb. I couldn't figure out if they had tested that isolate for pyrazinamide resistance.

Seen in  [10.4103/ijmy.ijmy_187_17](https://pubmed.ncbi.nlm.nih.gov/29516881/) where they characterised the activity of pyrazinamidase mutants. They saw loss of pyrazinamidase function:
_Among the 23 tested PncA mutants, 11 consisted of enzymes expressed from clinical isolates classified as PZA resistant by the phenotypic method. Seven of them (V9G, T47P, H51P, H51R, H57D, L85R, and **T142R**) were characterized by a lack of PZase activity while they displayed in vitro expression levels comparable to those of the control enzymes_

### Summary
The mutation is very rare, seen only once in WGS dataset and mentioned only a few times in publications.
Mutations in the same codon are already in the list as resistane conferrring (Thr142Ala, Thr142Lys, Thr142Met, Thr142Pro) indicating this position is highly relevant for resistance. Additionally the characterisation of PZase function showed that this mutation caused diminished activity.

I would suggest to **add** this mutation to the library.

**Comment by pmenzel** [comment]
> The mutation is very rare, seen only once in WGS dataset

Where did you look up the occurance of mutations in WGS datasets? Is there a database of genomes?

We will probably generate some more TB sequencing datasets and are interested to publish them if we find other novel or rare mutations associated with resistance phenotypes..

**Comment by jodyphelan** [comment]
I have a database of ~16,000 genomes which I used to benchmark tb-profiler [here](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-019-0650-x). I use these to scan when new resistance mutations are proposed. 

Great, do let us know if you find any more interesting mutations, it is really helpful!

I will wait a little bit to see if any of the other reviewers have thoughts and then add it in.

**Comment by pmenzel** [comment]
Ah cool, I will read your paper. We are also interested in doing ONT sequencing + TB-profiler.

In case we find any future novel mutations (i.e. not in TBDB) with a culture-verified resistance profile, would it be okay to just do another pull request here?

**Comment by pmenzel** [comment]
ps, thanks for all the work on TB-Profiler!

**Comment by jodyphelan** [comment]
No probs, I'm happy to contribute!

> In case we find any future novel mutations (i.e. not in TBDB) with a culture-verified resistance profile, would it be okay to just do another pull request here?

Yeah definitely, this is the right place for discussing new mutations!

**Comment by conmeehan** [comment]
PZA mutations are so difficult to be sure about, but I think better to flag it than leave it, so I agree with the addition.

**Comment by pmenzel** [comment]
Just to be clear, we this mutation was the only one found in pncA by TB-profiler and the isolate tested resistent for pyrozinamide in the antibiogram.

Here is the full output of TB-profiler:
```

TBProfiler report
=================

The following report has been generated by TBProfiler.

Summary
-------
ID: I304_Q4_074_AFtb4287_2020_MD_QFX
Date: Sun Sep  6 18:42:14 2020
Strain: root
Drug-resistance: Sensitive

Lineage report
--------------
Lineage	Estimated Fraction	Family	Spoligotype	Rd



Resistance report
-----------------
Drug	Genotypic Resistance	Mutations
Isoniazid		
Rifampicin		
Ofloxacin		
Capreomycin		
Fluoroquinolones		
Amikacin		
Cycloserine		
Streptomycin		
Ciprofloxacin		
Clofazimine		
Kanamycin		
Delamanid		
Ethambutol		
Pyrazinamide		
Linezolid		
Levofloxacin		
Moxifloxacin		
Aminoglycosides		
Bedaquiline		
Para-aminosalicylic acid		
Ethionamide		


Resistance variants report
-----------------
Genome Position	Locus Tag	Gene	Change	Estimated Fraction	Drug



Other variants report
---------------------
Genome Position	Locus Tag	Gene	Change	Estimated Fraction
7362	Rv0006	gyrA	p.Glu21Gln	1.000
7585	Rv0006	gyrA	p.Ser95Thr	1.000
9304	Rv0006	gyrA	p.Gly668Asp	0.993
491742	Rv0407	fgd1	c.960T>C	1.000
759358	Rv0667	rpoB	c.-449A>AT	0.038
759358	Rv0667	rpoB	c.-449A>G	0.019
759361	Rv0667	rpoB	c.-446CTT>C	0.123
759363	Rv0667	rpoB	-444TGG>*	0.041
759363	Rv0667	rpoB	c.-444TGG>T	0.020
759365	Rv0667	rpoB	c.-442G>GGGCGGTT	0.041
759365	Rv0667	rpoB	-442G>*	0.020
759746	Rv0667	rpoB	c.-61C>T	1.000
762434	Rv0667	rpoB	c.2628T>G	1.000
763031	Rv0667	rpoB	c.3225T>C	1.000
764343	Rv0668	rpoC	p.Arg325His	0.076
764345	Rv0668	rpoC	326PM>326HR	0.075
764352	Rv0668	rpoC	p.Val328Ala	0.078
781395	Rv0682	rpsL	c.-165T>C	1.000
1673349	Rv1483	fabG1	c.-91G>C	0.070
1673349	Rv1483	fabG1	c.-91G>GTGGC	0.007
1673357	Rv1483	fabG1	c.-83G>A	0.082
1673357	Rv1483	fabG1	c.-83G>T	0.007
1673359	Rv1483	fabG1	c.-81T>C	0.082
1673380	Rv1483	fabG1	c.-60C>G	0.134
1673380	Rv1483	fabG1	c.-60C>CTGGG	0.004
1674399	Rv1484	inhA	c.198A>G	0.995
1833403	Rv1630	rpsA	c.-139G>GA	0.149
1833414	Rv1630	rpsA	c.-128AT>A	0.130
1917972	Rv1694	tlyA	c.33A>G	1.000
2154724	Rv1908c	katG	p.Arg463Leu	1.000
2288817	Rv2043c	pncA	p.Thr142Arg	1.000
2715440	Rv2416c	eis	c.-108A>C	0.106
2715444	Rv2416c	eis	c.-112CT>T	0.106
2715448	Rv2416c	eis	c.-116TGA>A	0.106
2715449	Rv2416c	eis	-117CAGCGACGAATTTCGCCGTGACGTT>*	0.101
2726105	Rv2428	ahpC	c.-88G>A	1.000
3086788	Rv2780	ald	c.-32T>C	1.000
3841590	Rv3423c	alr	c.-170G>A	1.000
3841652	Rv3423c	alr	c.-232A>T	0.143
3841654	Rv3423c	alr	c.-234A>C	0.139
3841662	Rv3423c	alr	c.-242A>G	0.205
3841663	Rv3423c	alr	c.-243G>A	0.150
4242075	Rv3793	embC	p.Arg738Gln	0.992
4242643	Rv3793	embC	c.2781C>T	0.992
4245938	Rv3794	embA	c.2706C>T	0.993
4246544	Rv3795	embB	p.Thr11Pro	0.414
4246548	Rv3795	embB	p.Pro12Gln	0.497
4246555	Rv3795	embB	c.42G>C	0.517
4246563	Rv3795	embB	p.Leu17Trp	0.464
4246567	Rv3795	embB	c.54G>T	0.457
4246780	Rv3795	embB	c.267C>G	0.982
4246805	Rv3795	embB	c.292 293insCA	0.068
4407588	Rv3919c	gid	c.615T>C	1.000
1305494	Rv1173	fbiC	Chromosome:g.1305494 1305500del	1


Analysis pipeline specifications
--------------------------------
Version: 2.5.0
Analysis	Program
Mapping	bwa
Variant Calling	GATK


Disclaimer
----------
This tool is for Research Use Only and is offered free foruse. The London School
of Hygiene and Tropical Medicine shall have no liability for any loss or damages
of any kind, however sustained relating to the use of this tool.

Citation
--------
Coll, F. et al. Rapid determination of anti-tuberculosis drug resistance from
whole-genome sequences. Genome Medicine 7, 51. 2015

```

**Comment by jodyphelan** [comment]
Ok thanks, I will merge this in now.

**Pull request merged**
