### PR TITLE
add mutations from issue #15

### PR DESCRIPTION
**Pull request by jodyphelan**
Some new mutations

### CODE REVIEW

**Comment by jodyphelan** [comment]
After looking at these mutations here are my thoughts:


| Drug | Gene | Mutation | Comment | Recommendation |
|-|-|-|-|-|
|isoniazid|Rv1908c|p.Arg632Cys|Rare with little validation work but not a phylogenetic mutation| Include |
|ethionamide|Rv3854c|p.Ser266Arg| Looks like phylogenetic mutation | Exclude |
|kanamycin|Rv2416c|c.-6G>T|Only seen in combination with r.1401a>g. Possible low level resistance? |Include|
|isoniazid|Rv1908c|p.Trp351*|Rare with little validation work but very probably mechanism through loss of function| Include |
|kanamycin|Rv2416c|c.-15C>T|Can't find this mutation in the provided literature|Exclude|
|rifampicin|Rv0667|p.His445Leu|RRDR|Include|
|rifampicin|Rv0667|p.His445Tyr|RRDR|Include|
|rifampicin|Rv0667|p.Ser450Leu|RRDR|Include|
|isoniazid|Rv1908c|p.Asp329Ala|Rare with little validation work but not a phylogenetic mutation|Include |
|ethionamide|Rv3854c|p.Asn345Lys|Looks like phylogenetic mutation| Exclude |
|isoniazid|Rv1908c|p.Met420Thr|Rare with little validation work but not a phylogenetic mutation| Include|

**Comment by camusnimmo** [comment]
> After looking at these mutations here are my thoughts:
> 
> Drug	Gene	Mutation	Tree	Comment	Recommendation
> isoniazid	Rv1908c	p.Arg632Cys		Rare with little validation work but not a phylogenetic mutation	Include
**Cannot find evidence for this elsewhere, but agree could include**

> ethionamide	Rv3854c	p.Ser266Arg
Looks like phylogenetic mutation	Exclude
**Agree**

> kanamycin	Rv2416c	c.-6G>T		Only seen in combination with r.1401a>g. Possible low level resistance?	Include
**If not found in any other samples, and only seen in combination with known high confidence resistance conferring mutations, that is not enough evidence to say it is resistance conferring itself and so I would exclude**

> isoniazid	Rv1908c	p.Trp351*		Rare with little validation work but very probably mechanism through loss of function	Include
**Agree**

> kanamycin	Rv2416c	c.-15C>T		Can't find this mutation in the provided literature	Exclude
**Found this in the paper but in a strain with MICs below critical concentration therefore susceptible. Exclude**

> rifampicin	Rv0667	p.His445Leu		RRDR	Include
> rifampicin	Rv0667	p.His445Tyr		RRDR	Include
> rifampicin	Rv0667	p.Ser450Leu		RRDR	Include
**Include all - are they not in there already?**

> isoniazid	Rv1908c	p.Asp329Ala		Rare with little validation work but not a phylogenetic mutation	Include
**Does seem rare. Reported in this study, but only tested for low level resistance and did not do WGS - just fabG1 promoter and katG, therefore cannot excluded oxyR-ahpC mutations. Perhaps insufficient evidence on this basis?**

> ethionamide	Rv3854c	p.Asn345Lys	Looks like phylogenetic mutation	Exclude
**Agree**

> isoniazid	Rv1908c	p.Met420Thr		Rare with little validation work but not a phylogenetic mutation	Include
**As for Arg632Cys, not found elsewhere but could include**

**Comment by jodyphelan** [comment]
Thanks @camusnimmo. I'll merge in the mutations we both voted to include.

**Comment by jodyphelan** [comment]
Just to add... the rpoB mutations are already in the library through a wildcard-like specification whereby any mutation in the RRDR confers resistance.

**Pull request merged**
